### ISSUE TITLE
Computation graph replacements and aggregation schemes

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#514]
When I apply dropout to a computation graph  in which certain variables have aggregation schemes, this makes no changes to aggregation schemes. I find it very unfortunate and very dangerous.

I think that we could teach `ComputationGraph.replace` to make replacements in aggregation scheme inputs.

**Comment by dwf** [comment]
Can you explain a little more? As far as I understand it aggregation schemes are something used by monitoring. You almost always want to be monitoring the non-dropped-out version of the model.

**Comment by rizar** [comment]
An addition: same problem for auxiliary variables, they also must be changed.

@dwf, I am sort of used to always monitor the training cost on every batch in addition to the validation cost. Monitoring both dropped out cost and clean cost is very computationally expensive, that's why I want to monitor 
clean validation cost but dropped out training cost.

Aggregation schemes (`blocks/monitoring/aggregation.py`) are a way to define what is the right way to average your variable over a few batches. For instance if you monitor the cost per sequence element and you want to get average over ten batches, you have to sum ten total costs, sum all masks and divide the former by the latter. The aggregation schemes are handled in `AggregationBuffer` and `DatasetEvaluator`, which are in `blocks/monitoring/evaluators.py`.

**Comment by dmitriy-serdyuk** [comment]
@rizar , are you applying aggregations after replacements? Seems, that it should work.

**Comment by rizar** [comment]
@dmitriy-serdyuk , I am applying replacements after I attached aggregation schemes to some variables, and this does not work. I want to monitor similar expressions on training and vaidation data, with the difference that the former are monitored with regulazarion, and the latter without.

**Comment by rizar** [comment]
Thinking about it a bit more, the problem is that annotations are not affected by `ComputationGraph.replace`. That involves their auxiliary variables and updates and might have very nasty consequences, when updates added to the computation graph and invalidated by a transformation performed on it. Aggregation schemes in fact should inherit from `Annotation`, it's just that they were historically earlier introduced that they do not. 

I am thinking in the direction that the `Annotation` interface should be expanded with a `replace` method:

```python
class Annotation(object):

    def replace(self, updates, auxiliary_variables):
         """Create a clone of this annotation with new updates and auxiliary variables."""
         return Annotation(updates, auxiliary_variables)
```

For annotations such as `Brick`, it should simply `return self`, but for `ApplicationCall` and `AggregationScheme` it should produce a clone with the variables given.

**Comment by dwf** [comment]
@rizar is this resolved by #516?

**Comment by rizar** [comment]
No, #516 is orthogonal. Graph replacement are still not applied to auxiliary variables as they were.

**Comment by sotelo** [comment]
I also think that some improvements to the current aggregation scheme could be handy. For instance, what if we want to track the mean and median (or mean and variance) of some variables. Right now, I don't think this is supported unless you write appropiate AggregationSchemes which is kind of a hacky solution.

I think that it should be possible to monitor several aggregation schemes per variable and I would be willing to work on this if you guys think is useful as well.

**Comment by rizar** [comment]
Assuming that you have an aggregation scheme for median, I think it is very possible:

```python 
x = tensor.scalar('x')
mean_x = aggregation.mean(x)
mean_x.name = 'mean_x'
median_x = aggregation.median(x) # creates a copy to which an aggr. scheme is attached
median_x.name = 'median_x'
# now you can e.g. monitor both of them
```

**Comment by sotelo** [comment]
I see. Thanks for the answer.

When you compute the variance, you are usually computing the mean as well. If we do something like that for mean and variance, the computation will be repeated, is that right?

**Comment by rizar** [comment]
In principle Theano should optimize such repetitions away, and I think it will happen in practice.
